# Etapa 1: build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiar todo el proyecto
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

# Etapa 2: runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .

# Puerto que usará el contenedor
EXPOSE 8080

# Variable de entorno para producción
ENV ASPNETCORE_URLS=http://+:8080

# Inicia la API
ENTRYPOINT ["dotnet", "DOCHUB.API.dll"]
